### ISSUE TITLE
Deployment to Homebrew

### ISSUE THREAD

**Issue by simon-isler** [mhutter/sbb#10]
Would be quite nice to have it available on Homebrew. I saw you already did something in https://github.com/mhutter/sbb/pull/4?

**Comment by mhutter** [comment]
Indeed, and I have this already implemented for other projects. Should be easy to implement this here as well 👍 

I'll look into it

**Comment by simon-isler** [comment]
Nice, thanks! 🚀

**Comment by mhutter** [comment]
And done: 

    brew install mhutter/tap/sbb
